import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./components/context/CartContext";
import ClientLayout from "./ClientLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Next application",
    description: "This is a app from curso Next-js",
    type: "article",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <CartProvider>
            <ClientLayout>
              {children}
            </ClientLayout>
          </CartProvider>
        </div>
      </body>
    </html>
  );
}
